name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_SERVICE_NAME: codefc-mylinks
  OUTPUT_ARTIFACT: '.'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: back/
      
    - name: Build
      run: dotnet build --no-restore    
      working-directory: back/
      
    - name: Publish
      run: dotnet publish -c Release -o '${{env.OUTPUT_ARTIFACT}}/drop' --no-restore    
      working-directory: back/
    
    - name: 'Publicação no App Services'
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{env.APP_SERVICE_NAME}}'
        publish-profile: '${{secrets.MY_LINKS_PUBLISH_PROFILE}}'
        package: '${{env.OUTPUT_ARTIFACT}}/drop'
