name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_SERVICE_NAME: codefc-mylinks

jobs:
  build:
    name: "Continuous Integration"
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'back/MyLinks.API'
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: 'back/MyLinks.API'
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/drop'
      
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: '${{env.APP_SERVICE_NAME}}'        
        publish-profile: '${{ secrets.MY_LINK_PUBLISH_PROFILE }}'
        package: '${{ github.workspace }}/drop'
        
