name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_SERVICE_NAME: codefc-mylinks
  OUTPUT_ARTIFACT: '..'

jobs:
  "Continuos Intetration":

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: dotnet build and publish
      working-directory: 'back/MyLinks.API' 
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ github.workspace }}/drop' 
      
    #- name: Publish
    #  run: dotnet publish -c Release -o '${{env.GITHUB_WORKSPACE}}/drop' --no-restore    
    #  working-directory: back/MyLinks.API/
  
  "Continuous Deployment":
    runs-on: ubuntu-latest
    steps:
    - name: 'Publicação no App Services'    
      uses: azure/webapps-deploy@v2      
      with:
        app-name: '${{env.APP_SERVICE_NAME}}'
        publish-profile: '${{secrets.MY_LINKS_PUBLISH_PROFILE}}'
        package: '${{ github.workspace }}/drop' 
